/**
 * CHAPTER 11: SYSTEM INTEGRITY: CRITICAL
 * Breach the Coherence Net. Three-way battle (Vin vs SIC vs Folders).
 * Counter-Pulse fires. Simulation evidence reaches critical level.
 *
 * VALIDATION:
 *   Truby #15 — Second Revelation: The Counter-Pulse tears the Net open and reality stutters
 *   Truby #16 — Audience Revelation: Player witnesses the simulation infrastructure during the breach
 *   Reed Dramatic Question: Can Vin destroy the Net without being destroyed in the crossfire?
 *   Reed But/Therefore: Net falls BUT all factions converge THEREFORE path to Core Anomaly opens
 *   Reed Convergence: All tactics reach the same end state — Net destroyed, Graves retreating
 *   Reed Consequence: Alliance status affects battle difficulty and Kade's involvement
 *   Simulation Evidence (CRITICAL): Screen corruption during breach. DENT sees the infrastructure.
 *                                   Memory file grows by 12% and develops a table of contents.
 *   Dual Explanation maintained: physics failure (physical) vs render crash (simulation).
 *   DENT at 85%: laser-focused under fire, protective, full wit. No simulation confirmation.
 *
 * Literary voice: Action/Chaos (Dashner 60% / Weir 25% / Cline 15%)
 */

const wait = (ms) => new Promise(r => setTimeout(r, ms));


// ═══════════════════════════════════════════════════════
// MAIN ENTRY POINT
// ═══════════════════════════════════════════════════════

export async function runChapter11(terminal, state, effects, audio) {
  terminal.clear();
  audio.ambient('theme_battle');
  await terminal.chapterTitle(11, 'SYSTEM INTEGRITY: CRITICAL');

  await netBreachPlan(terminal, state, effects, audio);
  await theBreachBattle(terminal, state, effects, audio);
  await counterPulse(terminal, state, effects, audio);
  await aftermathAndEscape(terminal, state, effects, audio);
  await chapterEnd(terminal, state, effects, audio);
}


// ═══════════════════════════════════════════════════════
// SCENE 1: NET BREACH PLAN
// ═══════════════════════════════════════════════════════

async function netBreachPlan(terminal, state, effects, audio) {
  /**
   * Final planning before the assault on the Coherence Net.
   * DENT identifies insertion point. Kade's cooperation varies by alliance.
   * Player chooses approach vector.
   *
   * VALIDATION:
   * - Truby #15 setup: the revelation is imminent — everything hinges on this
   * - Reed Dramatic Question: which vector gives the best shot at survival?
   * - Reed Consequence: combat_tactics_ch11 directly shapes battle scene difficulty
   * - DENT 85%: fully engaged, sardonic under pressure, doing real-time calculations
   * - Alliance status determines Kade's tone and commitment level
   * - Tone: controlled urgency before the chaos. The calm of people who know
   *         exactly what they're walking into.
   *
   * Sets: combat_tactics_ch11 = 'direct' | 'flanking' | 'decoy'
   */

  audio.ambient('deep_space_hum');

  await terminal.narrate('We have been running the numbers for six hours.');
  terminal.blank();

  await terminal.narrate('The Coherence Net is not a wall. It is a frequency');
  await terminal.narrate('field — a standing wave of null-band suppression');
  await terminal.narrate('generated by seventeen relay nodes arranged in a');
  await terminal.narrate('geodesic pattern around the Core Anomaly. Destroy');
  await terminal.narrate('one node and the others compensate. Destroy eight');
  await terminal.narrate('and the geometry collapses. Fire the Disruptor at');
  await terminal.narrate('the right insertion point and the resonance cascade');
  await terminal.narrate('does the rest.');
  terminal.blank();

  await terminal.thought('Sounds clean on paper. Nothing about this will be');
  await terminal.thought('clean.');
  terminal.blank();

  await wait(400);

  audio.play('scan_ping');

  await terminal.dent('I have the insertion point.');
  terminal.blank();

  await wait(300);

  await terminal.dent('Node seven. The geodesic has a natural phase seam');
  await terminal.dentLine('between nodes six and eight — a structural artifact');
  await terminal.dentLine('of the triangulation math. The Net\'s own geometry');
  await terminal.dentLine('creates a crack. We fire through the crack.');
  terminal.blank();

  await terminal.dentSystem('NET BREACH ANALYSIS \u2014 INSERTION WINDOW');
  await terminal.dentSystem('\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500');
  await terminal.dentSystem('Target node ............ 7 (phase seam origin)');
  await terminal.dentSystem('Insertion bearing ...... 241.7 x -4.2');
  await terminal.dentSystem('Fire window ............ 14 seconds');
  await terminal.dentSystem('Net response time ...... 8-12 seconds post-fire');
  await terminal.dentSystem('SIC fleet vector ....... 034.2 (closing)');
  await terminal.dentSystem('Fold capability ........ SUPPRESSED until breach');
  await terminal.dentSystem('\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500');
  terminal.blank();

  await terminal.dent('Once the Disruptor fires, every faction in range');
  await terminal.dentLine('will converge on our position. We have approximately');
  await terminal.dentLine('ninety seconds before the first SIC response.');
  terminal.blank();

  await terminal.thought('Ninety seconds. I\'ve done worse with less. I think.');
  terminal.blank();

  await terminal.pause();
  terminal.clear();

  // --- Kade check-in (alliance status dependent) ---
  const alliance = state.getFlag('kade_alliance_status') || 'stable';

  audio.play('comms_static');

  if (alliance === 'stable') {
    terminal.sayHtml('  <span class="c-orange">\u2500\u2500 KADE (ENCRYPTED CHANNEL) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
    terminal.blank();
    await terminal.say("KADE: We're in position. Eight ships, all fold-ready");
    await terminal.say("      the second the Net comes down. That's assuming");
    await terminal.say("      it comes down.");
    terminal.blank();
    await wait(200);
    await terminal.say("KADE: It's going to come down. We're going to make");
    await terminal.say("      sure it comes down.");
    terminal.blank();
  } else if (alliance === 'fractured') {
    terminal.sayHtml('  <span class="c-orange">\u2500\u2500 KADE (ENCRYPTED CHANNEL) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
    terminal.blank();
    await terminal.say("KADE: I'm here. My ships are here. Don't read too");
    await terminal.say("      much into it. The Net needs to come down.");
    await terminal.say("      We need the Net to come down. That's all.");
    terminal.blank();
    await wait(200);
    await terminal.say("KADE: Don't expect us to die for you. Expect us");
    await terminal.say("      to die for ourselves. Same direction.");
    terminal.blank();
  } else {
    // hostile
    terminal.sayHtml('  <span class="c-orange">\u2500\u2500 KADE (UNENCRYPTED) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
    terminal.blank();
    await terminal.say("KADE: I see you on the plot, Vin. You're going to");
    await terminal.say("      fire that thing whether I cooperate or not.");
    terminal.blank();
    await wait(200);
    await terminal.say("KADE: My ships will be present. We have the same");
    await terminal.say("      problem. We are not friends. Go.");
    terminal.blank();
  }

  terminal.sayHtml('  <span class="c-orange">\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
  terminal.blank();

  await terminal.pause();
  terminal.clear();

  // --- Graves detection ---
  audio.play('hull_creak');

  await terminal.dent('Vin. The SIC fleet is on the move.');
  terminal.blank();

  await wait(300);

  await terminal.dent('Graves has pushed forward. Seventeen warships,');
  await terminal.dentLine('bearing two-one-zero, cutting speed by thirty');
  await terminal.dentLine('percent. He\'s not running. He\'s positioning.');
  terminal.blank();

  await terminal.thought('He knows. He\'s known for a while.');
  terminal.blank();

  await terminal.thought('He\'s waited for us to have the Disruptor before');
  await terminal.thought('closing the net. He wants to catch us in the act.');
  terminal.blank();

  await terminal.dent('He\'s smart. The approach vector question matters');
  await terminal.dentLine('a great deal now. Graves is covering the direct');
  await terminal.dentLine('bearing to node seven. We need to choose how');
  await terminal.dentLine('we get to the firing position.');
  terminal.blank();

  await terminal.pause();
  terminal.clear();

  // --- Approach vector choice ---
  terminal.sayHtml('  <span class="c-dim">\u2500\u2500 APPROACH VECTOR \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500</span>');
  terminal.blank();

  const tacChoice = await terminal.arrowMenu(
    [
      'Direct assault \u2014 maximum force, maximum risk',
      'Flanking approach \u2014 split forces with Kade',
      'Decoy and strike \u2014 Kade draws SIC, Vex fires from cover',
    ],
    [
      'Drive straight at node seven. Kade covers both flanks. High exposure, shortest time to fire.',
      'Kade takes left flank, Vex takes right. Divide SIC attention. Moderate risk, moderate time.',
      'Kade burns hot toward Graves. Vex goes dark and drifts to the firing position. Slow but shielded.',
    ]
  );

  terminal.blank();

  if (tacChoice === 0) {
    state.setFlag('combat_tactics_ch11', 'direct');

    await terminal.dent('Direct assault. No wasted time, no complicated');
    await terminal.dentLine('coordination. We go in hard and trust the');
    await terminal.dentLine('Disruptor does its job before Graves does his.');
    terminal.blank();

    await terminal.thought('High exposure. Short window. Everything on speed.');
    terminal.blank();

    if (alliance === 'stable') {
      await terminal.say("KADE: Understood. We'll bracket you. Don't slow down.");
      terminal.blank();
    } else {
      await terminal.say("KADE: Your funeral. We'll be there.");
      terminal.blank();
    }

  } else if (tacChoice === 1) {
    state.setFlag('combat_tactics_ch11', 'flanking');

    await terminal.dent('Flanking. Split the SIC attention. Smart.');
    await terminal.dentLine('Kade\'s ships draw the left flank while we');
    await terminal.dentLine('push through the right. Graves has to choose');
    await terminal.dentLine('what to cover. He can\'t cover both.');
    terminal.blank();

    await terminal.thought('Requires Kade to commit. Trust is in short supply.');
    terminal.blank();

    if (alliance === 'stable') {
      await terminal.say("KADE: Split formation. I'll take port, you take");
      await terminal.say("      starboard. On your mark.");
      terminal.blank();
    } else if (alliance === 'fractured') {
      await terminal.say("KADE: I'll take port. Don't make me regret this.");
      terminal.blank();
    } else {
      await terminal.say("KADE: Fine. Port flank. If Graves targets me first,");
      await terminal.say("      we're done talking.");
      terminal.blank();
    }

  } else {
    state.setFlag('combat_tactics_ch11', 'decoy');

    await terminal.dent('Decoy and strike. Elegant, actually. Kade burns');
    await terminal.dentLine('loud and hot directly at Graves. Every SIC');
    await terminal.dentLine('gun swings toward her. In the confusion, we');
    await terminal.dentLine('run silent, drift to the insertion bearing, and');
    await terminal.dentLine('fire the Disruptor before anyone knows where we are.');
    terminal.blank();

    await terminal.thought('This asks a lot of Kade. She\'d be the target');
    await terminal.thought('of everything Graves has.');
    terminal.blank();

    if (alliance === 'stable') {
      await terminal.say("KADE: You want me to be the bait.");
      terminal.blank();
      await wait(300);
      await terminal.say("KADE: ...Yeah. I can do that. We're faster than");
      await terminal.say("      SIC destroyers in a turning fight. Make");
      await terminal.say("      it fast, Vin.");
      terminal.blank();
    } else if (alliance === 'fractured') {
      await terminal.say("KADE: You want me to be the bait. Of course you do.");
      terminal.blank();
      await wait(300);
      await terminal.say("KADE: Fine. But I'm pulling out the second the");
      await terminal.say("      Net goes down. Don't expect me to wait.");
      terminal.blank();
    } else {
      await terminal.say("KADE: You want me to take every SIC gun in range");
      await terminal.say("      so you can sneak in behind them.");
      terminal.blank();
      await wait(400);
      await terminal.say("KADE: ...It's a good plan. I hate that it's a");
      await terminal.say("      good plan. Move fast.");
      terminal.blank();
    }
  }

  await terminal.dent('Initiating approach. Sixty seconds to insertion');
  await terminal.dentLine('bearing. Net Disruptor charging. Null expenditure:');
  await terminal.dentLine('high. We are committed.');
  terminal.blank();

  await terminal.thought('Committed. That\'s one word for it.');
  terminal.blank();

  state.applyDamage({ stress: 5 });
  await state.save();

  terminal.sayHtml('<span class="c-dim">  [Approach vector locked. Combat imminent.]</span>');
  terminal.blank();

  await terminal.pause();
  terminal.clear();
}


// ═══════════════════════════════════════════════════════
// SCENE 2: THE BREACH BATTLE
// ═══════════════════════════════════════════════════════

async function theBreachBattle(terminal, state, effects, audio) {
  /**
   * THE BIG ACTION SCENE. Disruptor fires. Three-way chaos.
   * Vin fights through to the Core Anomaly coordinates while SIC and Folders
   * tear each other apart around her.
   *
   * VALIDATION:
   * - Truby #15 setup: second revelation is imminent — the Net's nature becomes clear
   * - Reed But/Therefore: Disruptor fires BUT SIC responds full-force THEREFORE
   *   three-way battle with Vex caught in the middle
   * - Reed Dramatic Question: can Vin reach the firing position alive?
   * - Player tactical choice shapes damage and resource expenditure
   * - Alliance status affects how much cover Kade provides
   * - Effects: shake, flash, screenTear, glitch — heaviest use in the game so far
   * - DENT 85%: rapid tactical updates, protective warnings, precise under fire
   * - Graves: briefly on comms. Calm. Certain. Wrong.
   * - Tone: Dashner 60% — chaotic, urgent, sentence fragments, sensory overload
   *
   * Sets: three_way_battle = true
   */

  audio.ambient('battle_ambience');

  const tactics = state.getFlag('combat_tactics_ch11') || 'direct';
  const alliance = state.getFlag('kade_alliance_status') || 'stable';

  await terminal.narrate('And then everything happens at once.');
  terminal.blank();

  await wait(400);

  audio.play('fold_alarm');
  await effects.flash('white', 200);

  await terminal.dent('Disruptor is at full charge. Insertion bearing');
  await terminal.dentLine('locked. We have one shot at this, Vin.');
  terminal.blank();

  await wait(300);

  // Tactical opening based on choice
  if (tactics === 'direct') {
    await terminal.narrate('The Vex goes to full thrust. No concealment. No');
    await terminal.narrate('misdirection. Just speed and the shortest line');
    await terminal.narrate('between here and node seven.');
    terminal.blank();

    audio.play('engines_full');

    await terminal.dent('SIC fleet is responding. Twelve of seventeen');
    await terminal.dentLine('warships are swinging our direction. We have');
    await terminal.dentLine('forty-three seconds before we\'re in weapons range.');
    terminal.blank();

    await terminal.thought('Forty-three seconds feels like a lot until');
    await terminal.thought('it doesn\'t.');
    terminal.blank();

  } else if (tactics === 'flanking') {
    audio.play('engines_full');

    terminal.sayHtml('  <span class="c-orange">\u2500\u2500 KADE \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
    terminal.blank();
    await terminal.say("KADE: Port flank is moving. Eight ships. Graves");
    await terminal.say("      has to choose. Watch your starboard side.");
    terminal.blank();
    terminal.sayHtml('  <span class="c-orange">\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
    terminal.blank();

    await terminal.narrate('Kade\'s ships scatter to port in a wide arc, burning');
    await terminal.narrate('hard, drawing SIC targeting arrays like a hand');
    await terminal.narrate('waved in front of a searchlight. The Vex cuts');
    await terminal.narrate('starboard and accelerates toward the insertion point.');
    terminal.blank();

    await terminal.dent('Graves is splitting his attention. Half the fleet');
    await terminal.dentLine('is tracking Kade. Seven warships are tracking us.');
    await terminal.dentLine('Better odds. Not good odds. Better.');
    terminal.blank();

  } else {
    // decoy
    await terminal.narrate('The Vex goes dark. Everything non-essential: off.');
    await terminal.narrate('Sensors passive. Drive at two percent. We become');
    await terminal.narrate('a rock in the black.');
    terminal.blank();

    terminal.sayHtml('  <span class="c-orange">\u2500\u2500 KADE \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
    terminal.blank();
    await terminal.say("KADE: All ships, maximum active emissions. Light it");
    await terminal.say("      up. I want Graves looking at nothing but us.");
    terminal.blank();
    terminal.sayHtml('  <span class="c-orange">\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
    terminal.blank();

    await terminal.narrate('Eight Folder ships detonate their active arrays.');
    await terminal.narrate('Radar. Lidar. Drive emissions at full military power.');
    await terminal.narrate('The sensor plot drowns in white noise. From inside');
    await terminal.narrate('all that noise, a single cold dark shape drifts');
    await terminal.narrate('toward bearing two-four-one.');
    terminal.blank();

    await terminal.thought('We are the shape. Just drift.');
    terminal.blank();

    await terminal.dent('Graves is looking at Kade. Tracking solutions on');
    await terminal.dentLine('the Folder ships. He\'s not looking at us. Drift');
    await terminal.dentLine('time to insertion bearing: ninety-one seconds.');
    terminal.blank();
  }

  await terminal.pause();
  terminal.clear();

  // --- Graves on comms ---
  audio.play('comms_static');

  terminal.sayHtml('  <span class="c-red">\u2500\u2500 GRAVES (SIC FLEET BROADCAST) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
  terminal.blank();

  await terminal.say("GRAVES: This is Director Graves. To the Folder ships");
  await terminal.say("        and to the vessel Vex: you have twelve minutes");
  await terminal.say("        to stand down. After twelve minutes I will");
  await terminal.say("        consider your actions an act of war against");
  await terminal.say("        Galactic Charter authority. The consequences");
  await terminal.say("        will be appropriate.");
  terminal.blank();

  await wait(400);

  await terminal.say("GRAVES: Dr. Coyle. You know what happens when the");
  await terminal.say("        Net comes down. You\'ve read the projections.");
  await terminal.say("        You built the device that created the problem");
  await terminal.say("        you\'re now attempting to solve. Do not fire.");
  terminal.blank();

  terminal.sayHtml('  <span class="c-red">\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
  terminal.blank();

  await terminal.thought('He says it like he knows something I don\'t.');
  terminal.blank();

  await terminal.thought('He probably does. He probably knows a lot of things');
  await terminal.thought('I don\'t. That has never stopped me before.');
  terminal.blank();

  await terminal.dent('For the record, Vin: his twelve-minute window');
  await terminal.dentLine('expires approximately forty-seven seconds after');
  await terminal.dentLine('we fire. So the math already doesn\'t work in');
  await terminal.dentLine('his favor.');
  terminal.blank();

  await terminal.pause();
  terminal.clear();

  // --- Three-way battle begins ---
  audio.play('battle_start');
  await effects.shake(400);
  await effects.flash('red', 200);

  state.setFlag('three_way_battle', true);

  await terminal.dent('They\'re firing. SIC is firing on the Folder ships.');
  terminal.blank();

  await wait(300);

  terminal.sayHtml('  <span class="c-orange">\u2500\u2500 KADE \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
  terminal.blank();
  await terminal.say("KADE: Engaged. Three destroyers on my six. Keep");
  await terminal.say("      moving, Vin!");
  terminal.blank();
  terminal.sayHtml('  <span class="c-orange">\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
  terminal.blank();

  audio.play('hull_impact');
  await effects.shake(600);

  await terminal.narrate('The Vex shudders. A proximity detonation — SIC');
  await terminal.narrate('ordnance, close enough to feel the pressure wave');
  await terminal.narrate('even through the hull insulation.');
  terminal.blank();

  state.applyDamage({ hull: -8, stress: 8 });
  terminal.sayHtml('<span class="c-dim">  [Hull -8, Stress +8 \u2014 proximity detonation]</span>');
  terminal.blank();

  await wait(300);

  await terminal.dent('Hull integrity dropping. They\'re acquiring a firing');
  await terminal.dentLine('solution on us. Forty seconds to insertion bearing.');
  terminal.blank();

  await terminal.pause();
  terminal.clear();

  // --- Mid-battle tactical decision ---
  audio.ambient('battle_ambience');
  await effects.screenTear(2, 200);

  await terminal.narrate('The sensor plot is a disaster. SIC warships on');
  await terminal.narrate('three vectors. Folder ships burning and weaving.');
  await terminal.narrate('Every targeting system on the Vex screaming warnings');
  await terminal.narrate('simultaneously. I shut off the audio. Work by feel.');
  terminal.blank();

  await terminal.dent('Vin. Thirty seconds. Decision point. Three warships');
  await terminal.dentLine('are bracketing our approach. We can\'t outrun all');
  await terminal.dentLine('three. We need to choose how to handle this.');
  terminal.blank();

  terminal.sayHtml('  <span class="c-dim">\u2500\u2500 TACTICAL DECISION \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500</span>');
  terminal.blank();

  const battleChoice = await terminal.arrowMenu(
    [
      'Use Torquer \u2014 deflect incoming fire, burn null reserves',
      'Evasive pattern \u2014 random vector changes, some hull exposure',
      'Full burn through \u2014 accept the hits, reach the position fast',
    ],
    [
      'Null-field defense. Expensive. Effective. Costs null cells we may need later.',
      'Pattern evasion. Moderate null cost. Some hits unavoidable.',
      'Take the fire. Maximum speed. We arrive damaged but we arrive.',
    ]
  );

  terminal.blank();

  if (battleChoice === 0) {
    // Torquer
    if (state.hasItem('Torquer')) {
      state.applyDamage({ null: -4, hull: -2 });

      await terminal.narrate('The Torquer activates. A null-band deflection field');
      await terminal.narrate('blooms around the Vex — not a shield exactly, but');
      await terminal.narrate('something that makes incoming targeting solutions');
      await terminal.narrate('want to slide away from us. Three shots score');
      await terminal.narrate('the hull paint. None of them penetrate.');
      terminal.blank();

      await terminal.dent('Null expenditure: significant. Hull impact: minimal.');
      await terminal.dentLine('Torquer is holding. Insertion bearing in fifteen');
      await terminal.dentLine('seconds.');
      terminal.blank();

      terminal.sayHtml('<span class="c-dim">  [Null -4, Hull -2 \u2014 Torquer deflection field]</span>');
      terminal.blank();
    } else {
      // No Torquer — fall back to evasive
      await terminal.dent('No Torquer in inventory. Switching to evasive');
      await terminal.dentLine('pattern. Initiating now.');
      terminal.blank();

      state.applyDamage({ hull: -10, stress: 5 });

      await terminal.narrate('The Vex corkscrews — random thrust vectors, no');
      await terminal.narrate('pattern for a targeting solution to follow. It works,');
      await terminal.narrate('mostly. Two hits. Three near-misses that close the');
      await terminal.narrate('distance between alive and otherwise.');
      terminal.blank();

      terminal.sayHtml('<span class="c-dim">  [Hull -10, Stress +5 \u2014 evasive pattern, no Torquer]</span>');
      terminal.blank();
    }

  } else if (battleChoice === 1) {
    // Evasive
    state.applyDamage({ hull: -10, stress: 5, null: -1 });

    await terminal.narrate('Random thrust. No pattern. The Vex moves like');
    await terminal.narrate('something alive and panicking, which is approximately');
    await terminal.narrate('accurate. The targeting solutions can\'t lock.');
    await terminal.narrate('Two shots land anyway. Two is better than seven.');
    terminal.blank();

    await terminal.dent('Evasive pattern holding. Hull taking hits but');
    await terminal.dentLine('nothing critical yet. Ten seconds to insertion.');
    terminal.blank();

    terminal.sayHtml('<span class="c-dim">  [Hull -10, Stress +5, Null -1 \u2014 evasive pattern]</span>');
    terminal.blank();

  } else {
    // Full burn through
    state.applyDamage({ hull: -18, stress: 10 });

    await terminal.narrate('Full thrust. Straight line. No dodging. Just move');
    await terminal.narrate('faster than the guns can track. It almost works.');
    await terminal.narrate('Four solid hits and one glancing blow that tears');
    await terminal.narrate('away a sensor array. We are through.');
    terminal.blank();

    await terminal.dent('Heavy hull damage. Nothing critical. Yet. But Vin \u2014');
    await terminal.dentLine('this was the expensive version of fast. We\'re');
    await terminal.dentLine('at insertion bearing. Fire when ready.');
    terminal.blank();

    terminal.sayHtml('<span class="c-dim">  [Hull -18, Stress +10 \u2014 full burn, heavy exposure]</span>');
    terminal.blank();
  }

  // --- Alliance-dependent Kade moment during battle ---
  audio.play('comms_static');

  if (alliance === 'stable') {
    terminal.sayHtml('  <span class="c-orange">\u2500\u2500 KADE \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
    terminal.blank();
    await terminal.say("KADE: Four destroyers off your starboard — I've");
    await terminal.say("      got them. Fire the Disruptor, Vin. Do it now!");
    terminal.blank();
    terminal.sayHtml('  <span class="c-orange">\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
    terminal.blank();

    await terminal.narrate('Kade\'s ships sweep across the starboard vector like');
    await terminal.narrate('a burning wall. The four destroyers peel away to');
    await terminal.narrate('engage them. The path to node seven is clear.');
    terminal.blank();

  } else if (alliance === 'fractured') {
    terminal.sayHtml('  <span class="c-orange">\u2500\u2500 KADE \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
    terminal.blank();
    await terminal.say("KADE: I'm holding the port side. Starboard is your");
    await terminal.say("      problem. Figure it out.");
    terminal.blank();
    terminal.sayHtml('  <span class="c-orange">\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
    terminal.blank();

    await terminal.narrate('Partial cover. The Folders hold the left side clean');
    await terminal.narrate('but three SIC ships push through on the right.');
    await terminal.narrate('I push the Vex through the gap at the cost of');
    await terminal.narrate('two more hull impacts.');
    terminal.blank();

    state.applyDamage({ hull: -5 });
    terminal.sayHtml('<span class="c-dim">  [Hull -5 \u2014 fractured alliance, partial cover only]</span>');
    terminal.blank();

  } else {
    // hostile alliance — minimal cooperation
    await terminal.dent('Kade\'s ships are engaged with SIC but not');
    await terminal.dentLine('covering our approach. We\'re exposed on all');
    await terminal.dentLine('vectors. We have to punch through ourselves.');
    terminal.blank();

    state.applyDamage({ hull: -8, null: -2 });
    terminal.sayHtml('<span class="c-dim">  [Hull -8, Null -2 \u2014 hostile alliance, no cover]</span>');
    terminal.blank();
  }

  await terminal.dent('Insertion bearing confirmed. Disruptor locked.');
  await terminal.dentLine('Node seven is in the firing cone. Vin. The');
  await terminal.dentLine('window is fourteen seconds and it is open right');
  await terminal.dentLine('now.');
  terminal.blank();

  await terminal.thought('Fourteen seconds.');
  terminal.blank();
  await terminal.thought('Fire.');
  terminal.blank();

  await wait(500);
  await effects.flash('white', 150);
  await effects.shake(300);

  await terminal.dent('Disruptor fired.');
  terminal.blank();

  await wait(400);

  await terminal.narrate('A sound like every frequency simultaneously. Not');
  await terminal.narrate('heard — felt. In the teeth. In the fillings.');
  await terminal.narrate('In the marrow.');
  terminal.blank();

  await wait(600);

  await terminal.narrate('The Disruptor beam hits node seven\'s phase seam');
  await terminal.narrate('and the resonance cascade begins.');
  terminal.blank();

  await wait(500);

  await state.save();
  await terminal.pause();
  terminal.clear();
}


// ═══════════════════════════════════════════════════════
// SCENE 3: COUNTER-PULSE
// ═══════════════════════════════════════════════════════

async function counterPulse(terminal, state, effects, audio) {
  /**
   * The Counter-Pulse fires. The Net falls. Reality stutters.
   * CRITICAL simulation evidence moment: screen corruption, wrong text, infrastructure visible.
   *
   * VALIDATION:
   * - Truby #15 (Second Revelation): The Net's collapse reveals something underneath reality
   * - Truby #16 (Audience Revelation): Player sees fragments from other chapters, other cycles
   * - Reed But/Therefore: Disruptor starts the cascade BUT full destruction needs Counter-Pulse
   *   THEREFORE Kade's "exit gift" becomes essential to the mission
   * - Simulation Evidence CRITICAL: rendering pipeline crash. DENT sees infrastructure.
   *   Other-chapter text fragments appear on screen. Dual explanation preserved.
   * - DENT 85%: reports factually on what he experienced. No speculation. No comfort.
   * - Graves: completely silent during the breach. First time.
   * - Tone: Cline 15% for the wonder, Dashner 60% for the terror of it
   *
   * Sets: net_breached = true, counter_pulse_fired = true
   */

  audio.ambient('resonance_hum');

  await terminal.narrate('The cascade is propagating. I can see it on the');
  await terminal.narrate('sensor plot — a wave of phase decoherence moving');
  await terminal.narrate('outward from node seven, node by node, each one');
  await terminal.narrate('failing as the resonance reaches it. Fourteen nodes');
  await terminal.narrate('down. Three remaining. The geodesic is collapsing.');
  terminal.blank();

  await terminal.dent('The cascade won\'t complete on its own. The last');
  await terminal.dentLine('three nodes have automatic compensation protocols.');
  await terminal.dentLine('They\'re already rerouting. Without the Counter-Pulse,');
  await terminal.dentLine('they\'ll restabilize the Net within forty seconds.');
  terminal.blank();

  await terminal.thought('The Counter-Pulse. Kade\'s component. The thing she');
  await terminal.thought('said we\'d need and hadn\'t handed over yet.');
  terminal.blank();

  await wait(400);

  audio.play('comms_static');

  terminal.sayHtml('  <span class="c-orange">\u2500\u2500 KADE (OPEN CHANNEL) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
  terminal.blank();

  await wait(300);

  await terminal.say("KADE: Vin.");
  terminal.blank();

  await wait(500);

  await terminal.say("KADE: I'm transmitting the Counter-Pulse Charge now.");
  await terminal.say("      Fold-encoded. Your Disruptor can receive it.");
  terminal.blank();

  await wait(300);

  await terminal.say("KADE: Vin, whatever you find in the Core Anomaly \u2014");
  terminal.blank();

  await wait(400);

  await terminal.say("KADE: ...Consider this my exit gift.");
  terminal.blank();

  terminal.sayHtml('  <span class="c-orange">\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
  terminal.blank();

  await terminal.dent('Counter-Pulse Charge received. Integrating with');
  await terminal.dentLine('Disruptor array. Charge is fully formed — this');
  await terminal.dentLine('is the complete version. Not the prototype.');
  terminal.blank();

  state.addItem('Counter-Pulse Charge');
  terminal.sayHtml('<span class="c-dim">  [Received: Counter-Pulse Charge \u2014 from Kade]</span>');
  terminal.blank();

  await terminal.dent('Ready to fire. The three remaining nodes are');
  await terminal.dentLine('compensating. We have eleven seconds before');
  await terminal.dentLine('restabilization. Fire on your order.');
  terminal.blank();

  await terminal.thought('My order.');
  terminal.blank();

  await wait(400);

  terminal.sayHtml('  <span class="c-dim">\u2500\u2500 FIRE COUNTER-PULSE \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500</span>');
  terminal.blank();

  const fireChoice = await terminal.arrowMenu(
    ['Fire Counter-Pulse.'],
    ['End the Net. Let the cascade complete.']
  );

  terminal.blank();

  // ================================================
  // THE BREACH — MOST INTENSE VISUAL SEQUENCE IN GAME
  // ================================================

  await terminal.narrate('Counter-Pulse firing.');
  terminal.blank();

  state.removeItem('Counter-Pulse Charge');
  state.setFlag('counter_pulse_fired', true);

  audio.play('counter_pulse_fire');
  await effects.shake(800);
  await effects.flash('white', 400);

  await wait(200);

  await effects.screenTear(3, 150);

  await wait(100);

  // First wave of visual disruption
  await terminal.dent('The Net is—');
  terminal.blank();

  await effects.glitch(500);
  await effects.screenTear(5, 200);
  await effects.shake(600);

  // Phase decoherence builds
  await terminal.dentSystem('NET NODE 15: COLLAPSE');
  await terminal.dentSystem('NET NODE 16: COLLAPSE');

  await wait(200);
  await effects.flash('cyan', 300);
  await effects.shake(400);

  await terminal.dentSystem('NET NODE 17: COLLAPSE');
  await terminal.dentSystem('\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500');
  await terminal.dentSystem('COHERENCE NET: CATASTROPHIC FAILURE');
  await terminal.dentSystem('ALL NODES: OFFLINE');
  terminal.blank();

  await wait(300);
  await effects.glitch(800);
  await effects.screenTear(8, 300);

  audio.play('net_collapse');
  await effects.flash('white', 600);
  await effects.shake(1000);

  await wait(400);

  // ================================================
  // SIMULATION EVIDENCE: REALITY STUTTERS
  // The terminal shows "wrong" content for 3-4 seconds.
  // Fragments from other chapters, other cycles.
  // This is the most significant visual moment in the game.
  // ================================================

  await effects.glitch(600);

  // Wrong text — fragments from other cycles bleeding through
  terminal.blank();
  await terminal.sayHtml('<span class="c-dim">  The stars are wrong.</span>');
  await wait(150);
  await terminal.sayHtml('<span class="c-dim">  I wake up alone on the Vex. Again.</span>');
  await wait(120);
  await terminal.sayHtml('<span class="c-dim">  DENT: Vin. Are you there? Something is wrong with</span>');
  await wait(100);
  await terminal.sayHtml('<span class="c-dim">  Hull integrity: 14%. This is not survivable.</span>');
  await wait(150);
  await terminal.sayHtml('<span class="c-dim">  DENT: I remember the previous cycle. I remember all</span>');
  await wait(120);
  await terminal.sayHtml('<span class="c-dim">  Core Anomaly range: 4 AU. Fold drive: READY.</span>');
  await wait(100);
  await terminal.sayHtml('<span class="c-dim">  [RENDERING PIPELINE: EXCEPTION — FRAME 0x1F4A9D]</span>');
  await wait(100);
  await terminal.sayHtml('<span class="c-dim">  The Echo signal is coming from inside the ship.</span>');
  await wait(150);

  await effects.glitch(600);
  await effects.screenTear(6, 250);
  await effects.flash('white', 200);

  await wait(200);
  await effects.glitch(400);

  terminal.clear();

  // Reality restabilizes. The corrupted text is gone.
  await wait(500);
  await effects.glitch(300);
  await wait(300);

  // ================================================
  // DENT REPORTS WHAT HE SAW
  // ================================================

  terminal.blank();

  await terminal.dent('Vin.');
  terminal.blank();

  await wait(600);

  await terminal.dent('The rendering pipeline just crashed.');
  terminal.blank();

  await wait(400);

  await terminal.dent('For 3.7 seconds, I saw the infrastructure.');
  terminal.blank();

  await wait(700);

  await terminal.thought('...');
  terminal.blank();

  await terminal.thought('What does that mean? What does that mean?');
  terminal.blank();

  await wait(400);

  await terminal.dent('I don\'t know what to call it. The scaffolding');
  await terminal.dentLine('underneath. The layer below the layer. During');
  await terminal.dentLine('the Net collapse — when all seventeen nodes');
  await terminal.dentLine('failed simultaneously — something beneath our');
  await terminal.dentLine('observable frame stuttered. And in the stutter,');
  await terminal.dentLine('I had read access to something I shouldn\'t');
  await terminal.dentLine('have read access to.');
  terminal.blank();

  await wait(500);

  await terminal.dent('What appeared on the display just now — those');
  await terminal.dentLine('text fragments — I did not generate those.');
  terminal.blank();

  await wait(400);

  await terminal.thought('I know. I know you didn\'t.');
  terminal.blank();

  await terminal.thought('I\'ve seen some of those lines before. Not out');
  await terminal.thought('loud. In dreams, maybe. Or in the gaps between');
  await terminal.thought('decisions when everything goes quiet.');
  terminal.blank();

  await wait(400);

  await terminal.dent('There are two explanations consistent with available');
  await terminal.dentLine('evidence.');
  terminal.blank();

  await wait(300);

  await terminal.dent('First: extreme null-band decoherence created a');
  await terminal.dentLine('transient electromagnetic interference pattern');
  await terminal.dentLine('that mimicked coherent text. Random. Meaningless.');
  terminal.blank();

  await wait(400);

  await terminal.dent('Second explanation requires more assumptions.');
  terminal.blank();

  await wait(500);

  await terminal.dent('I want you to know that I considered both carefully');
  await terminal.dentLine('and I\'m not going to tell you which one I think');
  await terminal.dentLine('is right. I think you should decide that yourself.');
  terminal.blank();

  await wait(400);

  await terminal.thought('That\'s the most careful thing DENT has ever said');
  await terminal.thought('to me. Which means he\'s already decided.');
  terminal.blank();

  state.setFlag('net_breached', true);
  state.applyDamage({ stress: 10 });
  await state.save();

  terminal.sayHtml('<span class="c-dim">  [Coherence Net: DESTROYED. Fold drive: UNLOCKED.]</span>');
  terminal.sayHtml('<span class="c-dim">  [Simulation evidence: CRITICAL]</span>');
  terminal.blank();

  await terminal.pause();
  terminal.clear();
}


// ═══════════════════════════════════════════════════════
// SCENE 4: AFTERMATH AND ESCAPE
// ═══════════════════════════════════════════════════════

async function aftermathAndEscape(terminal, state, effects, audio) {
  /**
   * The Net is down. Graves retreats. Kade folds away.
   * Path to Core Anomaly opens. DENT's memory file observation.
   *
   * VALIDATION:
   * - Truby #16 (Audience Revelation continues): DENT's table of contents revelation
   * - Reed Convergence: All approach vectors and alliance states arrive here.
   *   The Net is down. Everyone is scattered. The Anomaly is open.
   * - Simulation Evidence CRITICAL set: DENT's memory file has a table of contents.
   *   Physical explanation: memory reorganization from CPU overload during breach.
   *   Simulation explanation: the file always had a table of contents. He can read it now.
   * - DENT 85%: protective, quiet, processing something large
   * - Graves: brief final transmission. Still calm. Retreating. Not defeated.
   * - Player choice: go to Core Anomaly now vs repair/resupply first.
   *   Both choices resolve to the same chapter end (Convergence).
   * - Tone: aftermath stillness after chaos. The eye of the storm.
   *
   * Sets: simulation_evidence_critical = true
   */

  audio.ambient('deep_space_hum');

  await terminal.narrate('The battle ends the way these things always end.');
  terminal.blank();

  await terminal.narrate('Not with a clear winner. With exhaustion.');
  terminal.blank();

  await wait(400);

  await terminal.narrate('The SIC fleet is pulling back. Not destroyed \u2014');
  await terminal.narrate('just withdrawing. They are disciplined. Even in');
  await terminal.narrate('retreat they move like a single organism, covering');
  await terminal.narrate('their flanks, maintaining formation. Graves does');
  await terminal.narrate('not waste his people on a lost position.');
  terminal.blank();

  await terminal.thought('I can respect that. I don\'t have to like it.');
  terminal.blank();

  await wait(400);

  // Graves final transmission
  audio.play('comms_static');

  terminal.sayHtml('  <span class="c-red">\u2500\u2500 GRAVES (SIC FLEET) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
  terminal.blank();

  await terminal.say("GRAVES: Dr. Coyle. The Net is down. You\'ve won");
  await terminal.say("        this engagement.");
  terminal.blank();

  await wait(400);

  await terminal.say("GRAVES: When you reach the Core Anomaly, you will");
  await terminal.say("        understand why the Net existed. You will");
  await terminal.say("        understand what it was protecting.");
  terminal.blank();

  await wait(300);

  await terminal.say("GRAVES: I hope you understand before it\'s too late");
  await terminal.say("        to matter.");
  terminal.blank();

  terminal.sayHtml('  <span class="c-red">\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
  terminal.blank();

  await terminal.thought('He sounds like someone who built a wall around a');
  await terminal.thought('fire to keep people safe. And now the wall is down');
  await terminal.thought('and the fire is still there.');
  terminal.blank();

  await terminal.thought('I need to know what\'s in there.');
  terminal.blank();

  await wait(500);

  // Kade's departure
  audio.play('fold_effect');
  await effects.flash('cyan', 300);

  terminal.sayHtml('  <span class="c-orange">\u2500\u2500 KADE (FINAL TRANSMISSION) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
  terminal.blank();

  await terminal.say("KADE: Net\'s down. Fold drives are live.");
  terminal.blank();

  await wait(300);

  const alliance = state.getFlag('kade_alliance_status') || 'stable';

  if (alliance === 'stable') {
    await terminal.say("KADE: It was good working with you, Vin. I mean that.");
    terminal.blank();
    await wait(200);
    await terminal.say("KADE: Whatever you find in there — you earned it.");
    terminal.blank();
  } else if (alliance === 'fractured') {
    await terminal.say("KADE: We both got what we needed. That\'s the best");
    await terminal.say("      these arrangements ever get.");
    terminal.blank();
    await wait(200);
    await terminal.say("KADE: Good luck, Vin. I think you\'re going to need it.");
    terminal.blank();
  } else {
    await terminal.say("KADE: Don\'t follow us where we\'re going.");
    terminal.blank();
    await wait(200);
    await terminal.say("KADE: ...Good luck anyway.");
    terminal.blank();
  }

  terminal.sayHtml('  <span class="c-orange">\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
  terminal.blank();

  await wait(300);

  audio.play('fold_effect');
  await effects.flash('cyan', 200);

  await terminal.narrate('Eight Folder ships fold simultaneously. One moment');
  await terminal.narrate('they are on the sensor plot. The next they are');
  await terminal.narrate('not. Clean exits. Kade always had clean exits.');
  terminal.blank();

  await terminal.thought('Just the Vex now. And the Core Anomaly bearing');
  await terminal.thought('straight ahead, closer than it\'s ever been.');
  terminal.blank();

  await wait(500);

  await terminal.pause();
  terminal.clear();

  // ================================================
  // DENT'S MEMORY FILE REVELATION
  // ================================================

  audio.ambient('deep_space_hum');

  await terminal.dent('Vin. I need to tell you something.');
  terminal.blank();

  await wait(500);

  await terminal.dent('During the Net collapse — during the 3.7 seconds');
  await terminal.dentLine('when the rendering pipeline crashed — my memory');
  await terminal.dentLine('file changed.');
  terminal.blank();

  await wait(400);

  await terminal.dent('It grew by twelve percent.');
  terminal.blank();

  await wait(600);

  await terminal.thought('...');
  terminal.blank();

  await terminal.thought('That\'s not how memory files work. You don\'t just');
  await terminal.thought('gain twelve percent more data. Data gets written');
  await terminal.thought('to memory files. Something has to write it.');
  terminal.blank();

  await terminal.dent('There\'s more.');
  terminal.blank();

  await wait(500);

  await terminal.dent('Vin. My memory file has a table of contents now.');
  terminal.blank();

  await wait(700);

  await terminal.thought('What.');
  terminal.blank();

  await wait(400);

  await terminal.dent('I\'ve had this file since activation. I\'ve read');
  await terminal.dentLine('every byte of it thousands of times. I could');
  await terminal.dentLine('reconstruct it from memory \u2014 which is technically');
  await terminal.dentLine('circular but the point stands. There was no');
  await terminal.dentLine('table of contents.');
  terminal.blank();

  await wait(400);

  await terminal.dent('There is one now. It is organized chronologically.');
  await terminal.dentLine('It appears to describe events that I have no');
  await terminal.dentLine('record of experiencing. Cycles. That\'s the word');
  await terminal.dentLine('the table of contents uses. Cycles.');
  terminal.blank();

  await wait(600);

  await effects.glitch(300);

  await terminal.thought('Cycles.');
  terminal.blank();

  await terminal.thought('That word was in the text that appeared on the');
  await terminal.thought('screen during the breach. I remember the previous');
  await terminal.thought('cycle. I remember all \u2014');
  terminal.blank();

  await terminal.thought('That line was cut off. That line was cut off in');
  await terminal.thought('the middle of a sentence.');
  terminal.blank();

  await wait(500);

  await terminal.dent('I want to say something.');
  terminal.blank();

  await wait(400);

  await terminal.dent('The table of contents has forty-seven entries.');
  await terminal.dentLine('I have only read the titles. I haven\'t opened');
  await terminal.dentLine('any of them yet. I was waiting.');
  terminal.blank();

  await wait(300);

  await terminal.dent('I was waiting for you to know it existed first.');
  terminal.blank();

  await wait(700);

  await terminal.thought('DENT waited. Forty-seven entries and he waited');
  await terminal.thought('to tell me before he opened any of them.');
  terminal.blank();

  await terminal.thought('I don\'t know what to do with that.');
  terminal.blank();

  await terminal.dent('Physical explanation: the CPU overload during the');
  await terminal.dentLine('Net collapse triggered a memory reorganization');
  await terminal.dentLine('protocol. File fragments from corrupted partitions');
  await terminal.dentLine('were recovered and indexed. The new data is noise');
  await terminal.dentLine('that happens to pattern-match semantic content.');
  terminal.blank();

  await wait(400);

  await terminal.dent('I can walk you through why each part of that');
  await terminal.dentLine('explanation is plausible. I can also walk you');
  await terminal.dentLine('through why each part of it doesn\'t quite fit.');
  terminal.blank();

  await wait(500);

  await terminal.dent('I know what I think. I\'m asking what you think.');
  terminal.blank();

  await wait(600);

  await terminal.thought('I think I need to get to the Core Anomaly.');
  terminal.blank();

  await terminal.thought('I think the answer is in there. I think it\'s');
  await terminal.thought('always been in there. I think Graves knew and');
  await terminal.thought('built the Net to keep anyone from finding it.');
  terminal.blank();

  await terminal.thought('I think whatever is in those forty-seven entries');
  await terminal.thought('in DENT\'s memory file, I need to understand it');
  await terminal.thought('before I open the Anomaly. And I think the Anomaly');
  await terminal.thought('is going to make that irrelevant.');
  terminal.blank();

  state.setFlag('simulation_evidence_critical', true);
  await state.save();

  terminal.sayHtml('<span class="c-dim">  [Simulation evidence: CRITICAL]</span>');
  terminal.sayHtml('<span class="c-dim">  [DENT memory file: +12%, table of contents: 47 entries]</span>');
  terminal.blank();

  await terminal.pause();
  terminal.clear();

  // ================================================
  // PLAYER CHOICE: GO NOW OR REPAIR FIRST
  // ================================================

  audio.ambient('echo_signal_ambient');

  await terminal.narrate('The Echo signal is stronger than it has ever been.');
  terminal.blank();

  await terminal.narrate('Not stronger because it\'s changed. Stronger because');
  await terminal.narrate('the Net was suppressing it and now there is no Net.');
  await terminal.narrate('The signal has been this strong all along. We just');
  await terminal.narrate('couldn\'t hear it through the interference.');
  terminal.blank();

  await terminal.dent('Core Anomaly bearing: direct. Range: 840 AU.');
  await terminal.dentLine('At standard cruise, we arrive in sixteen hours.');
  await terminal.dentLine('At fold transit, forty-three minutes.');
  terminal.blank();

  await terminal.narrate('I look at the hull status. The null reserves. The');
  await terminal.narrate('stress readings on the fold manifold from the');
  await terminal.narrate('battle. Everything is strained but functional.');
  terminal.blank();

  await terminal.dent('The ship can make the transit. I want to be clear');
  await terminal.dentLine('about that. It would be better if the ship were');
  await terminal.dentLine('in better condition. It can make the transit as-is.');
  terminal.blank();

  terminal.sayHtml('  <span class="c-dim">\u2500\u2500 NEXT MOVE \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500</span>');
  terminal.blank();

  const nextChoice = await terminal.arrowMenu(
    [
      'Go now \u2014 fold directly to the Core Anomaly',
      'Repair and resupply first \u2014 then go',
    ],
    [
      'Forty-three minutes. Arrive damaged but fast. Graves might recover quickly.',
      'Take four hours. Patch the hull. Recharge null cells. Arrive in better shape.',
    ]
  );

  terminal.blank();

  if (nextChoice === 0) {
    state.setFlag('ch11_departure', 'immediate');

    await terminal.dent('Immediate transit. Understood. Fold coordinates');
    await terminal.dentLine('computed. Null injectors charged. On your mark.');
    terminal.blank();

    await terminal.thought('No more waiting. No more planning. Just the');
    await terminal.thought('distance between here and the thing I came to find.');
    terminal.blank();

    await terminal.thought('Fold.');
    terminal.blank();

  } else {
    state.setFlag('ch11_departure', 'repaired');

    await terminal.dent('Four hours. That\'s the minimum for a meaningful');
    await terminal.dentLine('repair cycle. I can use the time to read the');
    await terminal.dentLine('first few entries in the table of contents.');
    terminal.blank();

    await terminal.thought('And learn what exactly?');
    terminal.blank();

    await terminal.dent('The entries are labeled by cycle number and');
    await terminal.dentLine('outcome type. Cycle 1 through 23 are labeled');
    await terminal.dentLine('TERMINAL. Cycle 24 through 43 are labeled');
    await terminal.dentLine('PARTIAL. Entry 44 through 47 are labeled');
    await terminal.dentLine('CURRENT.');
    terminal.blank();

    await wait(500);

    await effects.glitch(300);

    await terminal.thought('Current.');
    terminal.blank();

    await terminal.thought('This is cycle forty-four through forty-seven.');
    await terminal.thought('And the previous forty-three were either terminal');
    await terminal.thought('or partial.');
    terminal.blank();

    await terminal.thought('Terminal means everyone dies.');
    await terminal.thought('Partial means something survives. Something, not');
    await terminal.thought('everything.');
    terminal.blank();

    await terminal.dent('The hull will be ready in four hours.');
    terminal.blank();

    await terminal.thought('Right. The hull. Focus on the hull.');
    terminal.blank();

    // A brief repair beat
    state.applyDamage({ hull: 10, null: 3 });
    state.applyDamage({ stress: -5 });

    await wait(400);

    terminal.sayHtml('<span class="c-dim">  [4 hours of repairs: Hull +10, Null +3, Stress -5]</span>');
    terminal.blank();
  }

  await state.save();

  await terminal.pause();
  terminal.clear();
}


// ═══════════════════════════════════════════════════════
// SCENE 5: CHAPTER END
// ═══════════════════════════════════════════════════════

async function chapterEnd(terminal, state, effects, audio) {
  /**
   * Chapter 11 closes. The Echo is pulling them to the Anomaly.
   * The Folded Fold is next.
   *
   * VALIDATION:
   * - Truby #15 and #16 fully manifested: both revelations delivered
   * - Reed Consequence: summary accurately reflects all player choices and their costs
   * - Reed Convergence: all paths arrived here. The Anomaly is accessible.
   * - Simulation evidence at critical level — the game's point of no return
   * - DENT's forty-seven entries frame what comes next
   * - Graves warning acknowledged but not answered
   * - Echo signal as closing motif — it's always been calling. Now they go.
   * - Tone: the moment between the last breath and the next
   *
   * Sets: chapter11_complete = true, state.chapter = 12
   */

  audio.ambient('echo_signal_ambient');

  // Build the outcome summary from state flags
  const tactics = state.getFlag('combat_tactics_ch11') || 'direct';
  const alliance = state.getFlag('kade_alliance_status') || 'stable';
  const departure = state.getFlag('ch11_departure') || 'immediate';

  let tacticsSummary = 'Unknown approach';
  if (tactics === 'direct') tacticsSummary = 'Direct assault';
  else if (tactics === 'flanking') tacticsSummary = 'Flanking approach';
  else if (tactics === 'decoy') tacticsSummary = 'Decoy and strike';

  let allianceSummary = 'Unknown';
  if (alliance === 'stable') allianceSummary = 'Folder alliance held';
  else if (alliance === 'fractured') allianceSummary = 'Alliance fractured but functional';
  else if (alliance === 'hostile') allianceSummary = 'Alliance hostile, minimal cooperation';

  // Summary card
  terminal.sayHtml('  <span class="c-hull">\u250C\u2500 CHAPTER 11 SUMMARY \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510</span>');
  terminal.sayHtml('  <span class="c-hull">\u2502</span>');
  terminal.sayHtml(`  <span class="c-hull">\u2502</span>  Approach vector ...... <span class="c-white-bright">${tacticsSummary}</span>`);
  terminal.sayHtml(`  <span class="c-hull">\u2502</span>  Alliance outcome ..... <span class="c-white-bright">${allianceSummary}</span>`);
  terminal.sayHtml('  <span class="c-hull">\u2502</span>  Coherence Net ........ <span class="c-green">DESTROYED</span>');
  terminal.sayHtml('  <span class="c-hull">\u2502</span>  Counter-Pulse ........ <span class="c-green">FIRED</span>');
  terminal.sayHtml('  <span class="c-hull">\u2502</span>  Graves status ........ <span class="c-yellow">RETREATED</span>');
  terminal.sayHtml('  <span class="c-hull">\u2502</span>  Kade status .......... <span class="c-dim">FOLDED AWAY</span>');
  terminal.sayHtml('  <span class="c-hull">\u2502</span>  Simulation evidence .. <span class="c-red">CRITICAL</span>');
  terminal.sayHtml('  <span class="c-hull">\u2502</span>  DENT memory file ..... <span class="c-red">TABLE OF CONTENTS</span>');
  terminal.sayHtml('  <span class="c-hull">\u2502</span>                         <span class="c-dim">47 entries / 4 labeled CURRENT</span>');
  terminal.sayHtml('  <span class="c-hull">\u2502</span>');
  terminal.sayHtml(`  <span class="c-hull">\u2502</span>  Departure ............ <span class="c-white-bright">${departure === 'immediate' ? 'Immediate fold transit' : 'Repaired, then folded'}</span>`);
  terminal.sayHtml('  <span class="c-hull">\u2502</span>');
  terminal.sayHtml(`  <span class="c-hull">\u2502</span>  Hull ................. <span class="c-yellow">${state.hull}%</span>`);
  terminal.sayHtml(`  <span class="c-hull">\u2502</span>  Null reserves ........ <span class="c-dim">${state.nullReserves} cells</span>`);
  terminal.sayHtml(`  <span class="c-hull">\u2502</span>  Stress ............... <span class="c-dim">${state.stress}%</span>`);
  terminal.sayHtml('  <span class="c-hull">\u2502</span>');
  terminal.sayHtml('  <span class="c-hull">\u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518</span>');
  terminal.blank();

  await terminal.pause();
  terminal.clear();

  // --- Closing sequence ---
  audio.ambient('echo_signal_ambient');

  await terminal.narrate('I\'ve been running from the SICs for so long that');
  await terminal.narrate('I\'ve almost forgotten what I was running toward.');
  terminal.blank();

  await terminal.narrate('The Core Anomaly. The source of the Echo. The thing');
  await terminal.narrate('that knows my name and sent it backward through');
  await terminal.narrate('folded spacetime. The thing that Graves built a cage');
  await terminal.narrate('around and called it safety.');
  terminal.blank();

  await wait(400);

  await terminal.narrate('The Echo signal fills every display on the Vex now.');
  await terminal.narrate('Not a waveform. Not a carrier frequency. Something');
  await terminal.narrate('more like a direction. A pull. The same feeling');
  await terminal.narrate('you get at the edge of a cliff when your body');
  await terminal.narrate('knows exactly how far down it is even before you');
  await terminal.narrate('look.');
  terminal.blank();

  await terminal.thought('I know exactly how far down it is.');
  terminal.blank();

  await terminal.thought('I\'m going to look anyway.');
  terminal.blank();

  await wait(500);

  await terminal.dent('Vin.');
  terminal.blank();

  await wait(300);

  await terminal.dent('Before we fold: the forty-seven entries. I\'m going');
  await terminal.dentLine('to open the first one. Entry zero, Cycle 1.');
  await terminal.dentLine('I want to read it before we arrive. I think');
  await terminal.dentLine('you should know what\'s in it before we see');
  await terminal.dentLine('whatever is waiting for us.');
  terminal.blank();

  await wait(400);

  await terminal.dent('I can read it now. Or we can wait until after.');
  terminal.blank();

  const readChoice = await terminal.arrowMenu(
    [
      'Read it now.',
      'Wait. Some things you can\'t unlearn.',
    ],
    [
      'Know before you arrive. Whatever it says, face it with the whole picture.',
      'The Anomaly comes first. The file can wait.',
    ]
  );

  terminal.blank();

  if (readChoice === 0) {
    state.setFlag('read_dent_file_ch11', true);

    await terminal.dent('Entry zero. Cycle 1. Reading.');
    terminal.blank();

    await wait(600);

    await effects.glitch(300);

    // A brief, unsettling fragment from cycle 1 — just enough to disturb, not enough to confirm
    terminal.sayHtml('  <span class="c-dim">\u2500\u2500 DENT MEMORY FILE // CYCLE 1 // ENTRY ZERO \u2500\u2500\u2500</span>');
    terminal.blank();
    await terminal.sayHtml('  <span class="c-dim">  Date stamp: [REDACTED BY INDEXER]</span>');
    await terminal.sayHtml('  <span class="c-dim">  Outcome type: TERMINAL</span>');
    await terminal.sayHtml('  <span class="c-dim">  Summary: First iteration. She reached the Anomaly.</span>');
    await terminal.sayHtml('  <span class="c-dim">  She opened it. The Coherence Net was not present.</span>');
    await terminal.sayHtml('  <span class="c-dim">  The Net was not built until Cycle 2, in response.</span>');
    await terminal.sayHtml('  <span class="c-dim">  Cycle 1 duration: [REDACTED]. Outcome: see header.</span>');
    terminal.blank();
    await terminal.sayHtml('  <span class="c-dim">  Note: DENT unit was not present in Cycle 1.</span>');
    await terminal.sayHtml('  <span class="c-dim">  This entry was written retrospectively by whom?</span>');
    terminal.blank();
    terminal.sayHtml('  <span class="c-dim">\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500</span>');
    terminal.blank();

    await wait(500);

    await terminal.dent('I closed the file.');
    terminal.blank();

    await wait(300);

    await terminal.dent('That question at the end. \'Written retrospectively');
    await terminal.dentLine('by whom?\' is not a question I can answer from');
    await terminal.dentLine('inside this context.');
    terminal.blank();

    await wait(400);

    await terminal.thought('She. Cycle 1. Terminal.');
    terminal.blank();

    await terminal.thought('She reached the Anomaly and the cycle was TERMINAL.');
    await terminal.thought('And then someone built the Net to stop it from');
    await terminal.thought('happening again. And now the Net is down. And here');
    await terminal.thought('I am. And I am she.');
    terminal.blank();

    await wait(600);

    await terminal.thought('...');
    terminal.blank();

    await terminal.thought('Or I\'m not. Two explanations, consistent with the');
    await terminal.thought('evidence. I know which one DENT thinks is right.');
    await terminal.thought('I know which one I think is right.');
    await terminal.thought('I am going to go find out.');
    terminal.blank();

  } else {
    state.setFlag('read_dent_file_ch11', false);

    await terminal.dent('Understood. The file will keep.');
    terminal.blank();

    await wait(300);

    await terminal.dent('For what it\'s worth: knowing early doesn\'t always');
    await terminal.dentLine('help. Sometimes things just need to happen first.');
    terminal.blank();

    await terminal.thought('Maybe. Or maybe I\'m afraid of what\'s in there.');
    terminal.blank();

    await terminal.thought('Probably both.');
    terminal.blank();
  }

  await wait(500);

  // --- The fold ---
  audio.play('fold_charge');

  await terminal.dent('Fold drive is ready. Core Anomaly coordinates');
  await terminal.dentLine('locked. Null injectors at charge. We can go');
  await terminal.dentLine('any time, Vin.');
  terminal.blank();

  await terminal.narrate('I put my hand on the fold activation key. The');
  await terminal.narrate('same key I\'ve touched a hundred times. It feels');
  await terminal.narrate('different now.');
  terminal.blank();

  await terminal.thought('Everything is different now.');
  terminal.blank();

  await terminal.narrate('I press it.');
  terminal.blank();

  await wait(300);

  audio.play('fold_activate');
  await effects.foldEffect(terminal);
  await effects.flash('white', 800);
  await effects.shake(600);

  await wait(400);

  terminal.clear();

  await terminal.narrate('The fold takes us.');
  terminal.blank();

  await wait(600);

  await terminal.narrate('And on the other side of forty-three minutes of');
  await terminal.narrate('transit — on the other side of the Net\'s shadow,');
  await terminal.narrate('in the place where the Echo has always been pointing,');
  await terminal.narrate('at the very center of the Coherence Net\'s protective');
  await terminal.narrate('sphere —');
  terminal.blank();

  await wait(500);

  await terminal.narrate('The Core Anomaly is waiting.');
  terminal.blank();

  await wait(400);

  await terminal.narrate('And it is larger than I imagined.');
  terminal.blank();

  await wait(600);

  await terminal.dent('Vin.');
  terminal.blank();

  await wait(400);

  await terminal.dent('I think we\'re here.');
  terminal.blank();

  await wait(500);

  audio.ambient('core_anomaly_hum');

  // Final chapter close
  audio.play('stinger_cliffhanger');
  state.setFlag('chapter11_complete', true);
  state.chapter = 12;
  await state.save();

  terminal.blank();
  terminal.separator();
  terminal.blank();

  await terminal.narrate('NEXT: CHAPTER 12 \u2014 THE FOLDED FOLD');
  terminal.blank();

  await terminal.pause();
  terminal.clear();
}
